repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.5
    hooks:
      - id: terraform-fmt
      - id: gofmt
      # TODO:
      #- id: terraform-validate
      #- id: tflint
      #- id: shellcheck
      #- id: golint
